# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- task: Xcode@5
  displayName: 'Build the app using Xcode'
  inputs:
    actions: 'build'
    sdk: 'iphoneos'
    scheme: 'iOSHelloWorld'
    configuration: 'Debug'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    useXcpretty: 'false'

- task: Xcode@5
  displayName: 'Build the app using Xcode'
  inputs:
    actions: 'clean build analyze archive'
    sdk: 'iphoneos'
    scheme: 'iOSHelloWorld'
    configuration: 'Debug'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    useXcpretty: 'false'
    args: '-archivePath $(agent.buildDirectory)/iOSHelloWorld'

- task: ArchiveFiles@2
  displayName: 'Package .xcarchive into a zip file'
  inputs:
    rootFolderOrFile: '$(agent.buildDirectory)/iOSHelloWorld.xcarchive/'
    archiveFile: '$(build.artifactStagingDirectory)/iOSHelloWorld.xcarchive.zip'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/iOSHelloWorld.xcarchive.zip'
    artifactName: 'xcarchive-files'
    artifactType: 'container'
